name = "messagehub-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "CHANNEL"
class_name = "ChannelDurableObject"
